/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Content: typeof import('./src/components/Content/Content.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Goods: typeof import('./src/components/Goods/Goods.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Hot: typeof import('./src/components/Hot/Hot.vue')['default']
    Index: typeof import('./src/components/Index/Index.vue')['default']
    IndexBanner: typeof import('./src/components/IndexBanner/IndexBanner.vue')['default']
    IndexHot: typeof import('./src/components/IndexHot/IndexHot.vue')['default']
    IndexNew: typeof import('./src/components/IndexNew/IndexNew.vue')['default']
    IndexRecommend: typeof import('./src/components/IndexBanner/IndexRecommend.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    New: typeof import('./src/components/New/New.vue')['default']
    Register: typeof import('./src/components/Register/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Top: typeof import('./src/components/Top/Top.vue')['default']
  }
}
