/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CusTable: typeof import('./src/components/CusTable/CusTable.vue')['default']
    Detail: typeof import('./src/components/Detail/Detail.vue')['default']
    Goods: typeof import('./src/components/Manage/Goods.vue')['default']
    Hot: typeof import('./src/components/Hot/Hot.vue')['default']
    Index: typeof import('./src/components/Index/Index.vue')['default']
    IndexBanner: typeof import('./src/components/IndexBanner/IndexBanner.vue')['default']
    IndexRecom: typeof import('./src/components/IndexRecom/IndexRecom.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    MyCart: typeof import('./src/components/MyCart/MyCart.vue')['default']
    New: typeof import('./src/components/New/New.vue')['default']
    Order: typeof import('./src/components/Order/Order.vue')['default']
    Orders: typeof import('./src/components/Manage/Orders.vue')['default']
    OrderTable: typeof import('./src/components/OrderTable/OrderTable.vue')['default']
    Password: typeof import('./src/components/Manage/Password.vue')['default']
    Pay: typeof import('./src/components/Pay/Pay.vue')['default']
    ProductList: typeof import('./src/components/ProductList/ProductList.vue')['default']
    Register: typeof import('./src/components/Register/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Types: typeof import('./src/components/Manage/Types.vue')['default']
    User: typeof import('./src/components/User/User.vue')['default']
    Users: typeof import('./src/components/Manage/Users.vue')['default']
  }
}
